title: The anecdotes
description: > # this means to ignore newlines until "baseurl:"
  Blog with theme Future Imperfect<br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tlemsl.github.io/" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'minjong'
  last_name: 'kim'
  cv:
  avatar: '/images/avatar.jpeg'
  github_username:  tlemsl
  email: tlemsl@dgist.ac.kr
  vk_id:
  telegram_name:
  logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html
